# Generated by Django 5.2.8 on 2025-11-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('days_count', models.IntegerField()),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(max_length=64)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
